#Application Properties
spring.application.name=future-minds-backend
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/future_minds
spring.datasource.username=future_minds
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# prevents persistence sessions from being kept open into the presentation/web layer later.
spring.jpa.open-in-view=false
