CREATE TABLE parent_account (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    external_subject VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NULL,
    given_name VARCHAR(100) NULL,
    family_name VARCHAR(100) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
